export const FETCH_POSTS_LIST_START = 'FETCH_POSTS_LIST_START';
export const FETCH_POSTS_LIST_SUCCESS = 'FETCH_POSTS_LIST_SUCCESS';
export const FETCH_POSTS_LIST_FAIL = 'FETCH_POSTS_LIST_FAIL';
export const FETCH_POSTS_LIST_RESET = 'FETCH_POSTS_LIST_RESET';

export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';
export const FETCH_POST_RESET = 'FETCH_POST_RESET';

export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
