// flow-typed signature: 0a96c2d24fe1329cbf5756bba273fca4
// flow-typed version: <<STUB>>/webpack-uglify-js-plugin_v^1.1.9/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-uglify-js-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-uglify-js-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-uglify-js-plugin/example/build1/a.bundle' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build1/b.bundle' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build1/c.bundle' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build1/common' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build1/pages/a3.chunk-60b9faa90ccb0fa5efbc' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build1/pages/a4.chunk-60b9faa90ccb0fa5efbc' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/a.bundle' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/b.bundle' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/c.bundle' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/common' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/pages/a3.chunk-cb908a52ddc2578ddaff' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/pages/a4.chunk-cb908a52ddc2578ddaff' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/build2/pages/b3.chunk-cb908a52ddc2578ddaff' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/gulpfile' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/a.bundle.138e96669537827c2b57fe99665f6cb2fab9a1ed' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/b.bundle.353d34abc1361185f29506f4d3412187ddc450ce' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/b.bundle.a4564b7b088f251f0d5ed250486b5de6506045f3' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/c.bundle.645ce75e65a478d4cc37319ff05d3ea88814dd2a' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/common.a073b43d8221a18d6c80fa4f1857826eaf733527' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/common.e4f3c1538976f26b3ca59ab20d23707d9ae5bef0' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/a3.chunk-.26dfd527f3601793e2480333d9c79ccb47bdbdbf' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/a4.chunk-.9e9cb877d58438b0533bd13aeff19476023f5e54' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/b3.chunk-.0c201aefcebee15daba2367c4b63b4f937276a21' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/a' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/a1' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/a2' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/a3' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/a4' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/b' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/b1' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/b2' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/b3' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/src/c' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/example/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/utils/file' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/utils/genHash' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/utils/ModuleFilenameHelpers' {
  declare module.exports: any;
}

declare module 'webpack-uglify-js-plugin/utils/RequestShortener' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-uglify-js-plugin/example/build1/a.bundle.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build1/a.bundle'>;
}
declare module 'webpack-uglify-js-plugin/example/build1/b.bundle.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build1/b.bundle'>;
}
declare module 'webpack-uglify-js-plugin/example/build1/c.bundle.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build1/c.bundle'>;
}
declare module 'webpack-uglify-js-plugin/example/build1/common.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build1/common'>;
}
declare module 'webpack-uglify-js-plugin/example/build1/pages/a3.chunk-60b9faa90ccb0fa5efbc.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build1/pages/a3.chunk-60b9faa90ccb0fa5efbc'>;
}
declare module 'webpack-uglify-js-plugin/example/build1/pages/a4.chunk-60b9faa90ccb0fa5efbc.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build1/pages/a4.chunk-60b9faa90ccb0fa5efbc'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/a.bundle.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/a.bundle'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/b.bundle.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/b.bundle'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/c.bundle.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/c.bundle'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/common.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/common'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/pages/a3.chunk-cb908a52ddc2578ddaff.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/pages/a3.chunk-cb908a52ddc2578ddaff'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/pages/a4.chunk-cb908a52ddc2578ddaff.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/pages/a4.chunk-cb908a52ddc2578ddaff'>;
}
declare module 'webpack-uglify-js-plugin/example/build2/pages/b3.chunk-cb908a52ddc2578ddaff.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/build2/pages/b3.chunk-cb908a52ddc2578ddaff'>;
}
declare module 'webpack-uglify-js-plugin/example/gulpfile.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/gulpfile'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/a.bundle.138e96669537827c2b57fe99665f6cb2fab9a1ed.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/a.bundle.138e96669537827c2b57fe99665f6cb2fab9a1ed'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/b.bundle.353d34abc1361185f29506f4d3412187ddc450ce.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/b.bundle.353d34abc1361185f29506f4d3412187ddc450ce'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/b.bundle.a4564b7b088f251f0d5ed250486b5de6506045f3.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/b.bundle.a4564b7b088f251f0d5ed250486b5de6506045f3'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/c.bundle.645ce75e65a478d4cc37319ff05d3ea88814dd2a.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/c.bundle.645ce75e65a478d4cc37319ff05d3ea88814dd2a'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/common.a073b43d8221a18d6c80fa4f1857826eaf733527.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/common.a073b43d8221a18d6c80fa4f1857826eaf733527'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/common.e4f3c1538976f26b3ca59ab20d23707d9ae5bef0.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/common.e4f3c1538976f26b3ca59ab20d23707d9ae5bef0'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/a3.chunk-.26dfd527f3601793e2480333d9c79ccb47bdbdbf.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/a3.chunk-.26dfd527f3601793e2480333d9c79ccb47bdbdbf'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/a4.chunk-.9e9cb877d58438b0533bd13aeff19476023f5e54.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/a4.chunk-.9e9cb877d58438b0533bd13aeff19476023f5e54'>;
}
declare module 'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/b3.chunk-.0c201aefcebee15daba2367c4b63b4f937276a21.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/public/webpack_cached/cached_uglify/pages/b3.chunk-.0c201aefcebee15daba2367c4b63b4f937276a21'>;
}
declare module 'webpack-uglify-js-plugin/example/src/a.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/a'>;
}
declare module 'webpack-uglify-js-plugin/example/src/a1.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/a1'>;
}
declare module 'webpack-uglify-js-plugin/example/src/a2.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/a2'>;
}
declare module 'webpack-uglify-js-plugin/example/src/a3.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/a3'>;
}
declare module 'webpack-uglify-js-plugin/example/src/a4.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/a4'>;
}
declare module 'webpack-uglify-js-plugin/example/src/b.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/b'>;
}
declare module 'webpack-uglify-js-plugin/example/src/b1.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/b1'>;
}
declare module 'webpack-uglify-js-plugin/example/src/b2.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/b2'>;
}
declare module 'webpack-uglify-js-plugin/example/src/b3.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/b3'>;
}
declare module 'webpack-uglify-js-plugin/example/src/c.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/src/c'>;
}
declare module 'webpack-uglify-js-plugin/example/webpack.config.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/example/webpack.config'>;
}
declare module 'webpack-uglify-js-plugin/index' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin'>;
}
declare module 'webpack-uglify-js-plugin/index.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin'>;
}
declare module 'webpack-uglify-js-plugin/utils/file.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/utils/file'>;
}
declare module 'webpack-uglify-js-plugin/utils/genHash.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/utils/genHash'>;
}
declare module 'webpack-uglify-js-plugin/utils/ModuleFilenameHelpers.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/utils/ModuleFilenameHelpers'>;
}
declare module 'webpack-uglify-js-plugin/utils/RequestShortener.js' {
  declare module.exports: $Exports<'webpack-uglify-js-plugin/utils/RequestShortener'>;
}
